// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreatePostReq struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
}

type Post struct {
	ID          *int      `json:"id"`
	Title       *string   `json:"title"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
}
